name: Web CI/CD in Git
#What to trigger this action
on: push
#First job which gonna be execute
jobs:
  #job var which you can use in the above step
  build-node-express:
    # Name of the step
    name: Build Node
    # Which OS we gonna use
    runs-on: ubuntu-latest
    #Steps to execute 
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Set server as background process
        uses: BerniWittmann/background-server-action@v1
        with:
         cwd: ./Web
         start: npm start
         verbos: true
         #wait on the port
         wait-on: 'http://localhost:3000'
  build-java:
    name: Build Java
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
  start-wiremock-on-backgorund:
    runs-on: ubuntu-latest
    name: WireMock
    steps:
        - name: Set up WireMock as a standalone process
          uses: williamhaw/setup-wiremock-action@v0.1.2
          id: setup-wiremock
          with:
           http-port: '8080'
           mappings: 'example-mapping-directory'
           files: 'example-files-directory'
           command: 'node example.test.js'
           verbose: false
        - name: Get the WireMock standard output
          run: echo "${{ steps.setup-wiremock.outputs.wiremock-stdout }}"