name: Web CI/CD in Git
#What to trigger this action
on: push
#First job which gonna be execute
jobs:
  #job var which you can use in the above step
  build-node-express:
    # Name of the step
    name: Build Node
    # Which OS we gonna use
    runs-on: ubuntu-latest
    #Steps to execute 
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Set server as background process
        uses: BerniWittmann/background-server-action@v1
        with:
         cwd: ./Web
         start: npm start
         #wait on the port
         wait-on: 'http://localhost:3000'
  build-java:
    name: Build Java
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
  start-wiremock-on-backgorund:
    name: Start Wire Mock
    runs-on: ubuntu-latest
    steps:
      - name: Background server
        uses: BerniWittmann/background-server-action@v1
        with:
         cwd: ./WireMock
         start: java -jar wiremock-jre8-standalone-2.35.0.jar --port=8081 --https-port=8082
         #wait on the port
         wait-on: 'http://localhost:8081'