name: Node CI
on: push
jobs:
  build-node-express:
    name: Build Node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: BerniWittmann/background-server-action@v1
        name: Run node on background
        with:
         cwd: ./Web
         start: npm server.js
  build-java:
    name: Build Java
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - run: java -jar WireMock/wiremock-jre8-standalone-2.35.0.jar --port=8081 --https-port=8082
