name: Node CI
on: push
jobs:
  build-node-express:
    name: Build Node
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v2
      - run: npm install
        working-directory: ./Web
      - run: node Web/server.js
  build-java:
    name: Build Java
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - run: java --version