name: Web CI/CD in Git
#What to trigger this action
on: push
env:
  dir: ./LoginTest
#First job which gonna be execute
jobs:
  # #job var which you can use in the above step
  # build-node-express:
  #   # Name of the step
  #   name: Build Node
  #   # Which OS we gonna use
  #   runs-on: ubuntu-latest
  #   #Steps to execute 
  #   steps:
  #     - name: Checkout 
  #       uses: actions/checkout@v2
  #     - name: Set server as background process
  #       uses: BerniWittmann/background-server-action@v1
  #       with:
  #        cwd: ./Web
  #        start: npm start
  #        verbos: true
  #        #wait on the port
  #        wait-on: 'http://localhost:3000'
      # Verification of website content
      # - name: Puppeteer
      #   run: npm install puppeteer
      # - run: node openChrome.js
  # java-and-wiremock:
  #   runs-on: ubuntu-latest
  #   name: Set up WireMock as a standalone process
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Setup Java
  #       uses: actions/setup-java@v3
  #       with:
  #         distribution: 'temurin'
  #         java-version: '11'
  #     - name: Run WireMock
  #       uses: williamhaw/setup-wiremock-action@v0.1.2
  #       id: setup-wiremock
  #       with:
  #        http-port: '8080'
  #        mappings: 'WireMock/mappings'
  #        files: 'Wiremock/__files'
  #        #command: 'java -jar wiremock-jre8-standalone-2.35.0.jar --port=8081 --https-port=8082 --enable-stub-cors '
  #        verbose: false
  #     - name: Get the WireMock standard output
  #       run: echo "${{ steps.setup-wiremock.outputs.wiremock-stdout }}"
  install-dot-net:
    runs-on: windows-latest
    name: Install .Net
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
 
      - name: Install NUnit.ConsoleRunner
        run: nuget install NUnit.ConsoleRunner -Version 3.16.3

      - name: Run UnitTests
        working-directory: ./LoginTest
        run: nunit3-console.exe LoginTest\bin\Debug\LoginTest.dll
        
        