name: .NET CI

on:
  push:
    branches:
      - master
    build:
    runs-on: windows-latest

jobs:
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '3.1'

    - name: Build
      run: |
        dotnet restore
        dotnet build --configuration Release
jobs:
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: |
        ./mvnw clean install
