name: Node CI
on: push
jobs:
  build-node-express:
    name: Build Node
    runs-on: ubuntu-latest
    env: 
      API_PORT: 3000
    steps:
      - uses: actions/checkout@v2
      - uses: BerniWittmann/background-server-action@v1
        name: Run node on background
        with:
         run: |
           npm install &
           node Web/server.js &
         wait-on: |
            http://localhost:${{ env.API_PORT }}
            http-get://localhost:3000
        
         tail: true # true = stderr,stdout
            # This will allow you to monitor the progress live
  
         log-output-resume: stderr
            # Eliminates previosuly output stderr log entries from post-run output
  
         wait-for: 5m
  
         log-output: stderr,stdout # same as true
  
         log-output-if: failure
            # failure = exit-early or timeout
  
         working-directory: backend
  build-java:
    name: Build Java
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - run: java -jar WireMock/wiremock-jre8-standalone-2.35.0.jar --port=8081 --https-port=8082
